CV

In [5]:
from CV import EfficientNet, CVDataset
from torch.utils import data

In [6]:
en_b0 = EfficientNet()
animals_10_dataset = CVDataset("data/raw-img", 0.2, 0.1, en_b0.connector)
batch_size = 64

train_dataloader = data.DataLoader(
    data.Subset(animals_10_dataset, animals_10_dataset.train_index),
    batch_size=batch_size,
    shuffle=True,
    drop_last=True)
eval_dataloader = data.DataLoader(
    data.Subset(animals_10_dataset, animals_10_dataset.eval_index),
    batch_size=batch_size,
    shuffle=True,
    drop_last=True)
test_dataloader = data.DataLoader(
    data.Subset(animals_10_dataset, animals_10_dataset.test_index),
    batch_size=batch_size,
    shuffle=True,
    drop_last=True)

file, folder: e83db7072afd013ed1584d05fb1d4e9fe777ead218ac104497f5c978a4eebdbd_640.jpg, elephant


In [7]:
len(train_dataloader)

21

In [8]:
new_en_b0 = EfficientNet(new_head = True)
new_en_b0.train(train_dataloader, eval_dataloader, train_steps = 600)
new_en_b0.save("models/new_en_b0_first_run.pt")

In [9]:
mat, rep = new_en_b0.eval_statistics(test_dataloader)

In [10]:
print(mat)

[[18  0  0  0  0  0  0  0  0  0]
 [ 0 22  0  0  0  0  0  0  0  1]
 [ 0  0 27  0  0  0  0  0  0  0]
 [ 0  0  0 17  1  0  0  0  0  0]
 [ 0  0  0  0 18  0  0  0  0  0]
 [ 0  0  0  0  0 15  0  0  0  0]
 [ 0  0  0  0  0  0 21  0  0  0]
 [ 0  0  0  0  0  0  0 21  0  0]
 [ 0  0  0  0  0  0  0  0 12  0]
 [ 0  0  1  0  0  0  0  0  0 18]]


In [11]:
print(rep)

              precision    recall  f1-score   support

   butterfly       1.00      1.00      1.00        18
         cat       1.00      0.96      0.98        23
     chicken       0.96      1.00      0.98        27
         cow       1.00      0.94      0.97        18
         dog       0.95      1.00      0.97        18
    elephant       1.00      1.00      1.00        15
       horse       1.00      1.00      1.00        21
       sheep       1.00      1.00      1.00        21
      spider       1.00      1.00      1.00        12
    squirrel       0.95      0.95      0.95        19

    accuracy                           0.98       192
   macro avg       0.99      0.98      0.99       192
weighted avg       0.98      0.98      0.98       192



In [12]:
new_new_en_b0 = EfficientNet(new_head = True)
new_new_en_b0.load("models/new_en_b0_test.pt")

NER